In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
x = np.arange(10).reshape(-1, 1)
y = (2*x + 1).reshape(-1, 1)

In [7]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
y

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

## Model declaration, fit (training), predict (prediction)

In [9]:
model = LinearRegression()

In [12]:
model

LinearRegression()

In [10]:
model.fit(x, y)

LinearRegression()

In [13]:
prediction = model.predict([[10.0]])

In [14]:
prediction

array([[21.]])